version: '2.1'
services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
       container_name: elasticsearch
       environment:
          - discovery.type=single-node
       ports:
          - 9200:9200
          - 9300:9300
       networks:
          - docker-elk

     kibana:
       image: docker.elastic.co/kibana/kibana:7.2.0
       container_name: kibana
       environment:
          - SERVER_NAME=localhost
          - ELASTICSEARCH_URL=http://elasticsearch:9200/
       ports:
          - 5601:5601
       networks:
          - docker-elk

networks:
  docker-elk:
    driver: bridge